name: fluter_sample_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3 
  json_serializable: ^6.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
